/**
 * Scans examples/<component>/<name>.tsx and writes examples/__index__.tsx:
 * a map of "component/name" → { component, source } used by <ComponentPreview />.
 * Run automatically by `dev`, `build` and `typecheck`.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..", "examples");
const entries: { key: string; ident: string; source: string }[] = [];

for (const dir of readdirSync(root).sort()) {
  const full = join(root, dir);
  if (!statSync(full).isDirectory()) continue;
  for (const file of readdirSync(full).sort()) {
    if (!file.endsWith(".tsx")) continue;
    const name = file.replace(/\.tsx$/, "");
    const source = readFileSync(join(full, file), "utf8").replace(
      /^"use client";\s*\n+/,
      "",
    );
    entries.push({
      key: `${dir}/${name}`,
      ident: `E${entries.length}`,
      source,
    });
  }
}

const out = `// AUTO-GENERATED by scripts/build-examples.ts — do not edit.
import type { ComponentType } from "react";
${entries.map((e) => `import ${e.ident} from "./${e.key}";`).join("\n")}

export interface Example {
  component: ComponentType;
  source: string;
}

export const examples: Record<string, Example> = {
${entries.map((e) => `  ${JSON.stringify(e.key)}: { component: ${e.ident}, source: ${JSON.stringify(e.source)} },`).join("\n")}
};
`;

writeFileSync(join(root, "__index__.tsx"), out);
console.log(`examples/__index__.tsx: ${entries.length} examples`);
