/**
 * Scans examples/<component>/<name>.tsx and writes:
 *  - examples/__groups__/<component>.ts: that component's examples.
 *  - examples/__index__.tsx (client): `<Example name="component/name" />`,
 *    lazy-loading one group per component, so a page only downloads the
 *    examples of the components it shows (not all of them).
 *  - examples/__sources__.ts (server): `exampleSources`, the source shown in
 *    the docs. Keep it out of client components; it holds every file.
 * Run automatically by `dev`, `build` and `typecheck`.
 */
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..", "examples");
const entries: { key: string; dir: string; name: string; source: string }[] =
  [];

for (const dir of readdirSync(root).sort()) {
  const full = join(root, dir);
  if (/^[._]/.test(dir) || !statSync(full).isDirectory()) continue;
  for (const file of readdirSync(full).sort()) {
    // Skip dotfiles (e.g. macOS `._*` resource forks) and non-TSX files.
    if (file.startsWith(".") || !file.endsWith(".tsx")) continue;
    const name = file.replace(/\.tsx$/, "");
    const source = readFileSync(join(full, file), "utf8").replace(
      /^"use client";\s*\n+/,
      "",
    );
    entries.push({ key: `${dir}/${name}`, dir, name, source });
  }
}

const dirs = [...new Set(entries.map((e) => e.dir))];
const groupsDir = join(root, "__groups__");
rmSync(groupsDir, { recursive: true, force: true });
mkdirSync(groupsDir);
for (const dir of dirs) {
  const items = entries.filter((e) => e.dir === dir);
  writeFileSync(
    join(groupsDir, `${dir}.ts`),
    `// AUTO-GENERATED by scripts/build-examples.ts — do not edit.
import type { ComponentType } from "react";
${items.map((e, i) => `import E${i} from ${JSON.stringify(`../${e.key}`)};`).join("\n")}

export const examples: Record<string, ComponentType> = {
${items.map((e, i) => `  ${JSON.stringify(e.name)}: E${i},`).join("\n")}
};
`,
  );
}

const index = `// AUTO-GENERATED by scripts/build-examples.ts — do not edit.
"use client";

import { type ComponentType, lazy, Suspense } from "react";

type Group = { examples: Record<string, ComponentType> };

/** One chunk per component, holding all of its examples. */
const groups: Record<string, () => Promise<Group>> = {
${dirs.map((d) => `  ${JSON.stringify(d)}: () => import(${JSON.stringify(`./__groups__/${d}`)}),`).join("\n")}
};

const cache = new Map<string, ComponentType>();

function load(name: string): ComponentType | null {
  const cached = cache.get(name);
  if (cached) return cached;
  const [dir, example] = name.split("/");
  const group = groups[dir];
  if (!group || !example) return null;
  const Component = lazy(() =>
    group().then((m) => ({ default: m.examples[example] ?? Missing })),
  );
  cache.set(name, Component);
  return Component;
}

function Missing() {
  return null;
}

/** Renders the example \`name\` (e.g. "button/demo"), loading its chunk on demand. */
export function Example({ name }: { name: string }) {
  const Component = load(name);
  if (!Component) return null;
  return (
    <Suspense fallback={null}>
      <Component />
    </Suspense>
  );
}
`;

const sources = `// AUTO-GENERATED by scripts/build-examples.ts — do not edit.
// Server only: every example's source, as shown in the docs.

export const exampleSources: Record<string, string> = {
${entries.map((e) => `  ${JSON.stringify(e.key)}: ${JSON.stringify(e.source)},`).join("\n")}
};
`;

writeFileSync(join(root, "__index__.tsx"), index);
writeFileSync(join(root, "__sources__.ts"), sources);
console.log(
  `examples/__index__.tsx + __sources__.ts: ${entries.length} examples`,
);
